<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Verify Identity | Tourism Permit System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Inter', sans-serif;
            background: radial-gradient(circle at top right, #f8fafc, #e2e8f0);
            display: flex;
            align-items: center;
            min-height: 100vh;
            margin: 0;
        }
        .challenge-card {
            background: #ffffff;
            border: none;
            border-radius: 1.5rem;
            box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04);
        }
        .auth-icon-wrapper {
            width: 80px;
            height: 80px;
            background: #f1f5f9;
            border-radius: 50%;
            display: inline-flex;
            align-items: center;
            justify-content: center;
            margin-bottom: 1.5rem;
        }
        .otp-input {
            letter-spacing: 12px;
            font-size: 2.2rem !important;
            height: 80px;
            border: 2px solid #e2e8f0;
            border-radius: 12px;
            transition: all 0.2s ease;
            color: #1e293b;
        }
        .otp-input:focus {
            border-color: #0d6efd;
            box-shadow: 0 0 0 4px rgba(13, 110, 253, 0.1);
        }
        .btn-verify {
            padding: 1rem;
            font-weight: 600;
            border-radius: 12px;
            background: #1e293b;
            border: none;
            font-size: 1.1rem;
            transition: all 0.3s ease;
        }
        .btn-verify:hover {
            background: #0f172a;
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(0,0,0,0.15);
        }
        .back-link {
            color: #64748b;
            transition: color 0.2s;
            font-weight: 500;
        }
        .back-link:hover {
            color: #1e293b;
        }
    </style>
</head>
<body>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-5 col-lg-4">
            <div class="card challenge-card">
                <div class="card-body p-4 p-md-5 text-center">
                    
                    <div class="auth-icon-wrapper">
                        <img src="https://upload.wikimedia.org/wikipedia/commons/f/f7/Microsoft_Authenticator_logo.svg" width="45" alt="MS Auth">
                    </div>

                    <h3 class="fw-bold text-dark mb-2">Verify Identity</h3>
                    <p class="text-muted small mb-4 px-3">
                        Enter the 6-digit verification code generated by your <strong>Microsoft Authenticator</strong> app.
                    </p>

                    <form action="{{ route('admin.2fa.verify') }}" method="POST">
                        @csrf
                        <div class="mb-4">
                            <input type="text" 
                                   name="one_time_password" 
                                   class="form-control form-control-lg text-center fw-bold otp-input @error('one_time_password') is-invalid @enderror" 
                                   placeholder="000000" 
                                   maxlength="6" 
                                   pattern="\d*" 
                                   inputmode="numeric"
                                   required 
                                   autofocus 
                                   autocomplete="one-time-code">
                            
                            @error('one_time_password')
                                <div class="invalid-feedback fw-bold mt-2">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>

                        <button type="submit" class="btn btn-verify btn-primary w-100 shadow-sm">
                            Verify & Continue
                        </button>
                    </form>

                    <div class="mt-4">
                        <a href="{{ route('login') }}" class="text-decoration-none back-link small">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left me-1" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
                            </svg> Back to Login
                        </a>
                    </div>
                </div>
            </div>
            <p class="text-center mt-4 text-muted extra-small" style="font-size: 0.75rem;">
                Protected by Two-Factor Authentication
            </p>
        </div>
    </div>
</div>

</body>
</html>